### ISSUE TITLE
能介绍下使用的OS版本 Python版本吗

### ISSUE THREAD

**Issue by 121786404** [hey-yahei/GluonConverter#1]

**Comment by hey-yahei** [comment]
我是在Ubuntu18.04+Python3.7上测试的，由于代码大量使用了f-string，要求python版本必须大于等于3.6

**Comment by 121786404** [comment]
可是caffe只支持python3.5啊，在python3.7里面import caffe 有问题啊

**Comment by 121786404** [comment]
我跑classification.py 里面会import caffe

**Comment by hey-yahei** [comment]
不可能吧？我用python3.7来import caffe丝毫没有问题，另外先前版本的classification.py的protobuf pool会出现冲突（如果本地的caffe不是ssd版本的话），如果你也是报类似的错误建议重新clone最新的代码。

**Comment by 121786404** [comment]
好像不import caffe 也能转，先不用caffe了

**Comment by hey-yahei** [comment]
嗯嗯，import caffe是为了运行校对的程序（确保转换后的模型跟原始模型的输出一致），转换过程不需要caffe参与。
