### ISSUE TITLE
可以支持mobilenet_v2 和  squeezenet 吗？

### ISSUE THREAD

**Issue by 121786404** [hey-yahei/GluonConverter#2]
assert attrs['pooling_convention'] == 'valid', "Caffe only support Pooling layer with ceil_mode=False"
AssertionError: Caffe only support Pooling layer with ceil_mode=False

assert convert_fn is not None, f"unknwon op: {op}"
AssertionError: unknwon op: clip

**Comment by hey-yahei** [comment]
mobilenet_v2用了relu6，这个我找个时间支持一下；squeezenet恐怕凉凉，因为caffe的pooling没法做成ceil_mode的，这东西转换不过去。

**Comment by hey-yahei** [comment]
呃收回前言，其实caffe支持ceil_mode=True，只是我pool解析写错了，重新clone一下最新的代码就ok

**Comment by hey-yahei** [comment]
caffe-bvlc和caffe-ssd都不支持ReLU6也不支持clip，所以我只能暴力地把ReLU6改成ReLU（参考[tests/classification.py](https://github.com/hey-yahei/GluonConverter/blob/master/tests/classification.py#L20-L30)），但这样会导致精度有所下降。不过也有的caffe分支或者第三方平台是支持ReLU6的，如果你的模型要部署在这些分支或者平台上，可以手动把生成的prototxt里的`ReLU`都改为相应的type（比如`ReLU6`）。

**Comment by 121786404** [comment]
relu6 是不是转成clip层 比较合理？

**Comment by hey-yahei** [comment]
如果有clip，自然是clip更为合理，只可惜caffe-bvlc和caffe-ssd都没有提供clip层。
